# Markdownlint configuration
# Prefer readable line length but do not enforce hard wrap
MD013:
  line_length: 120
  code_blocks: false
  tables: false
  headings: false

# Allow inline HTML in specs (for tables/notes)
MD033: false

# Allow multiple headings with same name within different files
MD024:
  allow_different_nesting: true

# Require blank lines around headings
MD022: true

# Require ATX headings style
MD003:
  style: atx

# Unordered list style
MD004:
  style: dash

# Trailing spaces allowed only in code blocks
MD009:
  br_spaces: 0
  list_item_empty_lines: false

# Enforce fenced code blocks
MD046: true
