AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'specs/**/*'
    - 'vendor/**/*'
    - 'bin/binstubs/**/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'bin/rake'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/htmldiff'
    - 'bin/ldiff'
    - 'bin/racc'
    - 'bin/ruby-parse'
    - 'bin/ruby-rewrite'
  SuggestExtensions: false

plugins:
  - rubocop-rspec

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

RSpec:
  Language:
    Expectations:
      - expect

# ---------------------------
# Spec-specific relaxations
# ---------------------------
RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleExpectations:
  Max: 10

Metrics/CyclomaticComplexity:
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/**/*'

Layout/FirstArrayElementIndentation:
  Exclude:
    - 'spec/**/*'

Lint/RedundantCopDisableDirective:
  Exclude:
    - 'spec/**/*'
