name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ruby: [ '3.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install --path vendor/bundle

      - name: RuboCop
        run: bundle exec rubocop -f s

      - name: RSpec
        run: bundle exec rspec --format documentation

      - name: Validate JSON examples
        run: bundle exec rake validate:json

      - name: Validate XML examples
        run: bundle exec rake validate:xml

      - name: Smoke test (help/version)
        run: |
          bundle exec bin/pretty-git --help > /dev/null
          bundle exec bin/pretty-git --version
