name: Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rubocop
